In [1]:
import pandas as pd
from datetime import date

pd.set_option('display.max_columns', None)

In [2]:
# retrieve games from csv
all_games_df = pd.read_csv('etl/games.csv')
print(f'{len(all_games_df)} games retrieved')
print(f'Home teams in dataframe: {all_games_df['home_team'].nunique()}')
all_games_df.head()

5724 games retrieved
Home teams in dataframe: 154

,game_id,date,home_team,home_team_id,away_team,away_team_id,location,home_score,away_score,league,metro_area,metro_team_num,completed_flag,home_venue,venue_city,venue_capacity,venue_opened
0,NFL_2025_1,2025-09-05 00:20:00+00:00,Philadelphia Eagles,nfl_26,Dallas Cowboys,nfl_9,Lincoln Financial Field,24.0,20.0,nfl,"Philadelphia, Pennsylvania",nfl_1,0,Lincoln Financial Field,"Philadelphia, Pennsylvania",69596,2003
1,NFL_2025_2,2025-09-06 00:00:00+00:00,Los Angeles Chargers,nfl_18,Kansas City Chiefs,nfl_16,Arena Corinthians,27.0,21.0,nfl,"Los Angeles, California",nfl_1,0,SoFi Stadium,"Inglewood, California",70240,2020
2,NFL_2025_3,2025-09-07 17:00:00+00:00,Atlanta Falcons,nfl_2,Tampa Bay Buccaneers,nfl_30,Mercedes-Benz Stadium,NaN,NaN,nfl,"Atlanta, Georgia",nfl_1,1,Mercedes-Benz Stadium,"Atlanta, Georgia",71000,2017
3,NFL_2025_4,2025-09-07 17:00:00+00:00,Cleveland Browns,nfl_8,Cincinnati Bengals,nfl_7,Huntington Bank Field,NaN,NaN,nfl,"Cleveland, Ohio",nfl_1,0,Huntington Bank Field,"Cleveland, Ohio",67431,1999
4,NFL_2025_5,2025-09-07 17:00:00+00:00,Indianapolis Colts,nfl_14,Miami Dolphins,nfl_20,Lucas Oil Stadium,NaN,NaN,nfl,"Indianapolis, Indiana",nfl_1,0,Lucas Oil Stadium,"Indianapolis, Indiana",67000,2008

In [3]:
# convert to Central, tz naive
all_games_df['date'] = pd.to_datetime(all_games_df['date'], utc=True)
all_games_df['date'] = all_games_df['date'].dt.tz_convert(tz='US/Central')
all_games_df['date'] = all_games_df['date'].dt.tz_localize(None)

# separate date and datetime fields
all_games_df['datetime'] = all_games_df['date']
all_games_df['date'] = all_games_df['datetime'].dt.date

# preview df
all_games_df.head()

,game_id,date,home_team,home_team_id,away_team,away_team_id,location,home_score,away_score,league,metro_area,metro_team_num,completed_flag,home_venue,venue_city,venue_capacity,venue_opened,datetime
0,NFL_2025_1,2025-09-04,Philadelphia Eagles,nfl_26,Dallas Cowboys,nfl_9,Lincoln Financial Field,24.0,20.0,nfl,"Philadelphia, Pennsylvania",nfl_1,0,Lincoln Financial Field,"Philadelphia, Pennsylvania",69596,2003,2025-09-04 19:20:00
1,NFL_2025_2,2025-09-05,Los Angeles Chargers,nfl_18,Kansas City Chiefs,nfl_16,Arena Corinthians,27.0,21.0,nfl,"Los Angeles, California",nfl_1,0,SoFi Stadium,"Inglewood, California",70240,2020,2025-09-05 19:00:00
2,NFL_2025_3,2025-09-07,Atlanta Falcons,nfl_2,Tampa Bay Buccaneers,nfl_30,Mercedes-Benz Stadium,NaN,NaN,nfl,"Atlanta, Georgia",nfl_1,1,Mercedes-Benz Stadium,"Atlanta, Georgia",71000,2017,2025-09-07 12:00:00
3,NFL_2025_4,2025-09-07,Cleveland Browns,nfl_8,Cincinnati Bengals,nfl_7,Huntington Bank Field,NaN,NaN,nfl,"Cleveland, Ohio",nfl_1,0,Huntington Bank Field,"Cleveland, Ohio",67431,1999,2025-09-07 12:00:00
4,NFL_2025_5,2025-09-07,Indianapolis Colts,nfl_14,Miami Dolphins,nfl_20,Lucas Oil Stadium,NaN,NaN,nfl,"Indianapolis, Indiana",nfl_1,0,Lucas Oil Stadium,"Indianapolis, Indiana",67000,2008,2025-09-07 12:00:00

In [4]:
# filter games_df on uncompleted teams
games_df = all_games_df[all_games_df['completed_flag']==0]

# filter games located in home venue
games_df = games_df[games_df['location']==games_df['home_venue']]

# count remaining games, teams
print(f'Games remaining in dataframe: {len(games_df)}')
print(f'Home teams remaining in dataframe: {games_df['home_team'].nunique()}')

Games remaining in dataframe: 4528
Home teams remaining in dataframe: 127

In [5]:
# grouping by city and date, pivoting by metro team number to account for multiple games by same team
city_date_df = pd.pivot_table(games_df, values='home_team', index=['metro_area', 'date'],
                              columns='metro_team_num', aggfunc='nunique', fill_value=0).reset_index()

# remove extraneous "metro_team_num" column created by pivot_table
city_date_df.columns = [col for col in city_date_df.columns.values]

city_date_game_count = city_date_df.sort_values(by=['metro_area', 'date'])
city_date_game_count.head()

,metro_area,date,mlb_1,mlb_2,mls_1,mls_2,nba_1,nba_2,nfl_1,nfl_2,nhl_1,nhl_2,nhl_3
0,"Atlanta, Georgia",2025-02-22,0,0,1,0,0,0,0,0,0,0,0
1,"Atlanta, Georgia",2025-03-08,0,0,1,0,0,0,0,0,0,0,0
2,"Atlanta, Georgia",2025-03-16,0,0,1,0,0,0,0,0,0,0,0
3,"Atlanta, Georgia",2025-03-29,0,0,1,0,0,0,0,0,0,0,0
4,"Atlanta, Georgia",2025-04-05,0,0,1,0,0,0,0,0,0,0,0

In [6]:
# min and max dates in games data
min_date = city_date_game_count['date'].min()
max_date = city_date_game_count['date'].max()
print(f'min date: {min_date}, max date: {max_date}')

# city count
city_count = city_date_game_count['metro_area'].nunique()
print(f'city count: {city_count}')

min date: 2025-02-22, max date: 2026-04-16
city count: 46

In [7]:
# create list of dates that has each possible date in range
# extend that list however many times that there are cities
dates_idx = pd.date_range(start=min_date, end=max_date)
num_dates = len(dates_idx)
print(f'number of dates: {num_dates}')
for _ in range(city_count-1):
    dates_idx = dates_idx.append(pd.date_range(start=min_date, end=max_date))
print(f'length of date index: {len(dates_idx)}')

number of dates: 419
length of date index: 19274

In [8]:
# create list of cities in game data
# extend to have N of each city equal to number of dates in range
cities = list(set(city_date_game_count['metro_area']))
cities_mult = []
for city in cities:
    city_mult = [city] * num_dates
    cities_mult.extend(city_mult)
len(cities_mult)

19274

In [9]:
# create skeleton dataframe for all cities-dates
cities_dates_mult = pd.DataFrame({'metro_area':cities_mult, 'date':dates_idx}).sort_values(['metro_area', 'date']).reset_index(drop=True)
cities_dates_mult['date'] = pd.to_datetime(cities_dates_mult['date']).dt.date
cities_dates_mult.dtypes

metro_area    object
date          object
dtype: object

In [17]:
# merge dataframes to have number of teams active for every city-date
city_date_game_count_df = cities_dates_mult.merge(city_date_game_count, how='left', on=['metro_area','date'])

# updating logic to make metro_team_num column names dynamic
# handles if all teams of a certain metro_team_num are completed
team_cols = list(city_date_game_count_df.iloc[:,2:].columns.values)
city_date_game_count_df[team_cols] = city_date_game_count_df[team_cols].fillna(0)
city_date_game_count_df

,metro_area,date,mlb_1,mlb_2,mls_1,mls_2,nba_1,nba_2,nfl_1,nfl_2,nhl_1,nhl_2,nhl_3
0,"Atlanta, Georgia",2025-02-22,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,"Atlanta, Georgia",2025-02-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"Atlanta, Georgia",2025-02-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,"Atlanta, Georgia",2025-02-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"Atlanta, Georgia",2025-02-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19269,"Winnipeg, Manitoba",2026-04-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19270,"Winnipeg, Manitoba",2026-04-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19271,"Winnipeg, Manitoba",2026-04-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19272,"Winnipeg, Manitoba",2026-04-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19273,"Winnipeg, Manitoba",2026-04-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [18]:
# function to calculate games in N-day range
def day_range_game_counts(df, low_window:int, high_window:int, team_cols=team_cols):
    col_name = {1:'one', 2:'two', 3:'three', 4:'four', 5:'five', 6:'six'}
    dfs = []

    for window in range(low_window, high_window+1):
        dff = df.copy()

        # create column to calculate total teams in previous N days
        dff[team_cols] = dff.groupby(['metro_area'])[team_cols]\
                                                .rolling(window=window, min_periods=1).sum().reset_index(0, drop=True)

        # create column for beginning of date range
        dff['date'] = pd.to_datetime(dff['date'])
        dff[f'{col_name[window]}_day_start_date'] = dff['date'] - pd.Timedelta(f'{window-1} days')
        dff = dff.rename(columns={'date':f'{col_name[window]}_day_end_date'})
        dff = dff[['metro_area', f'{col_name[window]}_day_start_date', f'{col_name[window]}_day_end_date'] + team_cols]

        # combine new columns into 1 new column for N-day total
        dff[f'{col_name[window]}_day_total'] = dff[team_cols].clip(upper=1).sum(axis=1)

        # remove extraneous columns
        if window!=low_window:
            dff = dff.drop(columns=team_cols+['metro_area'])
        # else:
        #     dff = dff.drop(columns=team_cols+'metro_area')

        # append to list of dfs for concatenation
        dfs.append(dff)

    ranges_df = pd.concat(dfs, axis=1)
    return ranges_df

In [27]:
# testing top date ranges
cdgc_df = day_range_game_counts(city_date_game_count_df, 2, 6)
cdgc_df.sort_values('three_day_total', ascending=False)

,metro_area,two_day_start_date,two_day_end_date,mlb_1,mlb_2,mls_1,mls_2,nba_1,nba_2,nfl_1,nfl_2,nhl_1,nhl_2,nhl_3,two_day_total,three_day_start_date,three_day_end_date,three_day_total,four_day_start_date,four_day_end_date,four_day_total,five_day_start_date,five_day_end_date,five_day_total,six_day_start_date,six_day_end_date,six_day_total
11596,"New York City, New York",2025-12-01,2025-12-02,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,4.0,2025-11-30,2025-12-02,5.0,2025-11-29,2025-12-02,5.0,2025-11-28,2025-12-02,5.0,2025-11-27,2025-12-02,5.0
8635,"Los Angeles, California",2025-11-03,2025-11-04,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,3.0,2025-11-02,2025-11-04,5.0,2025-11-01,2025-11-04,5.0,2025-10-31,2025-11-04,5.0,2025-10-30,2025-11-04,5.0
11631,"New York City, New York",2026-01-05,2026-01-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,2026-01-04,2026-01-06,5.0,2026-01-03,2026-01-06,5.0,2026-01-02,2026-01-06,5.0,2026-01-01,2026-01-06,5.0
8634,"Los Angeles, California",2025-11-02,2025-11-03,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,4.0,2025-11-01,2025-11-03,5.0,2025-10-31,2025-11-03,5.0,2025-10-30,2025-11-03,5.0,2025-10-29,2025-11-03,5.0
8633,"Los Angeles, California",2025-11-01,2025-11-02,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,4.0,2025-10-31,2025-11-02,5.0,2025-10-30,2025-11-02,5.0,2025-10-29,2025-11-02,5.0,2025-10-28,2025-11-02,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10605,"Montreal, Quebec",2025-07-01,2025-07-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-06-30,2025-07-02,0.0,2025-06-29,2025-07-02,0.0,2025-06-28,2025-07-02,1.0,2025-06-27,2025-07-02,1.0
10606,"Montreal, Quebec",2025-07-02,2025-07-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-07-01,2025-07-03,0.0,2025-06-30,2025-07-03,0.0,2025-06-29,2025-07-03,0.0,2025-06-28,2025-07-03,1.0
10607,"Montreal, Quebec",2025-07-03,2025-07-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-07-02,2025-07-04,0.0,2025-07-01,2025-07-04,0.0,2025-06-30,2025-07-04,0.0,2025-06-29,2025-07-04,0.0
3455,"Cincinnati, Ohio",2025-06-04,2025-06-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-06-03,2025-06-05,0.0,2025-06-02,2025-06-05,0.0,2025-06-01,2025-06-05,0.0,2025-05-31,2025-06-05,1.0
9637,"Milwaukee, Wisconsin",2025-02-21,2025-02-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-02-20,2025-02-22,0.0,2025-02-19,2025-02-22,0.0,2025-02-18,2025-02-22,0.0,2025-02-17,2025-02-22,0.0

## Integrating with original games data to make 1 table for export

In [28]:
# filter down to just five day total column and then proceed as before
cdgc_df = cdgc_df.drop(columns=team_cols)
cdgc_df.head()

,metro_area,two_day_start_date,two_day_end_date,two_day_total,three_day_start_date,three_day_end_date,three_day_total,four_day_start_date,four_day_end_date,four_day_total,five_day_start_date,five_day_end_date,five_day_total,six_day_start_date,six_day_end_date,six_day_total
0,"Atlanta, Georgia",2025-02-21,2025-02-22,1.0,2025-02-20,2025-02-22,1.0,2025-02-19,2025-02-22,1.0,2025-02-18,2025-02-22,1.0,2025-02-17,2025-02-22,1.0
1,"Atlanta, Georgia",2025-02-22,2025-02-23,1.0,2025-02-21,2025-02-23,1.0,2025-02-20,2025-02-23,1.0,2025-02-19,2025-02-23,1.0,2025-02-18,2025-02-23,1.0
2,"Atlanta, Georgia",2025-02-23,2025-02-24,0.0,2025-02-22,2025-02-24,1.0,2025-02-21,2025-02-24,1.0,2025-02-20,2025-02-24,1.0,2025-02-19,2025-02-24,1.0
3,"Atlanta, Georgia",2025-02-24,2025-02-25,0.0,2025-02-23,2025-02-25,0.0,2025-02-22,2025-02-25,1.0,2025-02-21,2025-02-25,1.0,2025-02-20,2025-02-25,1.0
4,"Atlanta, Georgia",2025-02-25,2025-02-26,0.0,2025-02-24,2025-02-26,0.0,2025-02-23,2025-02-26,0.0,2025-02-22,2025-02-26,1.0,2025-02-21,2025-02-26,1.0

In [26]:
games_df.head(1)

,game_id,date,home_team,home_team_id,away_team,away_team_id,location,home_score,away_score,league,metro_area,metro_team_num,completed_flag,home_venue,venue_city,venue_capacity,venue_opened,datetime
0,NFL_2025_1,2025-09-04,Philadelphia Eagles,nfl_26,Dallas Cowboys,nfl_9,Lincoln Financial Field,24.0,20.0,nfl,"Philadelphia, Pennsylvania",nfl_1,0,Lincoln Financial Field,"Philadelphia, Pennsylvania",69596,2003,2025-09-04 19:20:00

In [29]:
full_join_df = cdgc_df.merge(games_df, on='metro_area')
print(len(games_df))
print(len(cdgc_df))
print(len(full_join_df))
full_join_df.head(1)

4528
19274
1897232

,metro_area,two_day_start_date,two_day_end_date,two_day_total,three_day_start_date,three_day_end_date,three_day_total,four_day_start_date,four_day_end_date,four_day_total,five_day_start_date,five_day_end_date,five_day_total,six_day_start_date,six_day_end_date,six_day_total,game_id,date,home_team,home_team_id,away_team,away_team_id,location,home_score,away_score,league,metro_team_num,completed_flag,home_venue,venue_city,venue_capacity,venue_opened,datetime
0,"Atlanta, Georgia",2025-02-21,2025-02-22,1.0,2025-02-20,2025-02-22,1.0,2025-02-19,2025-02-22,1.0,2025-02-18,2025-02-22,1.0,2025-02-17,2025-02-22,1.0,MLS_2025_3,2025-02-22,Atlanta United FC,mls_1,CF Montreal,mls_3,Mercedes-Benz Stadium,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00

In [30]:
# filters df to associate each game with all date ranges that the game falls in
games_counts_df = full_join_df[(full_join_df['date']>=full_join_df['five_day_start_date']) &
                               (full_join_df['date']<=full_join_df['five_day_end_date'])]\
                               .sort_values(['metro_area', 'date'])
print(len(games_counts_df))
games_counts_df.head(5)

22583

,metro_area,two_day_start_date,two_day_end_date,two_day_total,three_day_start_date,three_day_end_date,three_day_total,four_day_start_date,four_day_end_date,four_day_total,five_day_start_date,five_day_end_date,five_day_total,six_day_start_date,six_day_end_date,six_day_total,game_id,date,home_team,home_team_id,away_team,away_team_id,location,home_score,away_score,league,metro_team_num,completed_flag,home_venue,venue_city,venue_capacity,venue_opened,datetime
0,"Atlanta, Georgia",2025-02-21,2025-02-22,1.0,2025-02-20,2025-02-22,1.0,2025-02-19,2025-02-22,1.0,2025-02-18,2025-02-22,1.0,2025-02-17,2025-02-22,1.0,MLS_2025_3,2025-02-22,Atlanta United FC,mls_1,CF Montreal,mls_3,Mercedes-Benz Stadium,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
57,"Atlanta, Georgia",2025-02-22,2025-02-23,1.0,2025-02-21,2025-02-23,1.0,2025-02-20,2025-02-23,1.0,2025-02-19,2025-02-23,1.0,2025-02-18,2025-02-23,1.0,MLS_2025_3,2025-02-22,Atlanta United FC,mls_1,CF Montreal,mls_3,Mercedes-Benz Stadium,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
114,"Atlanta, Georgia",2025-02-23,2025-02-24,0.0,2025-02-22,2025-02-24,1.0,2025-02-21,2025-02-24,1.0,2025-02-20,2025-02-24,1.0,2025-02-19,2025-02-24,1.0,MLS_2025_3,2025-02-22,Atlanta United FC,mls_1,CF Montreal,mls_3,Mercedes-Benz Stadium,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
171,"Atlanta, Georgia",2025-02-24,2025-02-25,0.0,2025-02-23,2025-02-25,0.0,2025-02-22,2025-02-25,1.0,2025-02-21,2025-02-25,1.0,2025-02-20,2025-02-25,1.0,MLS_2025_3,2025-02-22,Atlanta United FC,mls_1,CF Montreal,mls_3,Mercedes-Benz Stadium,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
228,"Atlanta, Georgia",2025-02-25,2025-02-26,0.0,2025-02-24,2025-02-26,0.0,2025-02-23,2025-02-26,0.0,2025-02-22,2025-02-26,1.0,2025-02-21,2025-02-26,1.0,MLS_2025_3,2025-02-22,Atlanta United FC,mls_1,CF Montreal,mls_3,Mercedes-Benz Stadium,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00

In [31]:
# exporting results to use in Tableau
games_counts_df.to_csv('tableau/games_counts_data.csv', index=False)

TODO: create map

Have map switch between length of day ranges

If the goal is to have 5 days as max range and then look for shorter, is there a more dynamic way of finding the number of days within the date range that actually contain the games? Like if there's 3 in 5, but they're actually 3 days in a row, then it's a true 3-day range. But would that be thrown off by a team having more than 1 game in the range?

Is there a way to just add the number of "dead days" (days without game) in a date range? Because that might matter most.