In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = px.data.gapminder().query("year==2007")

In [3]:
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32
...,...,...,...,...,...,...,...,...
1655,Vietnam,Asia,2007,74.249,85262356,2441.576404,VNM,704
1667,West Bank and Gaza,Asia,2007,73.422,4018332,3025.349798,PSE,275
1679,"Yemen, Rep.",Asia,2007,62.698,22211743,2280.769906,YEM,887
1691,Zambia,Africa,2007,42.384,11746035,1271.211593,ZMB,894
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [4]:
games_df = pd.read_csv('games_counts_data.csv')
games_df

,metro_area,two_day_start_date,two_day_end_date,two_day_total,three_day_start_date,three_day_end_date,three_day_total,four_day_start_date,four_day_end_date,four_day_total,...,home_score,away_score,league,metro_team_num,completed_flag,home_venue,venue_city,venue_capacity,venue_opened,datetime
0,"Atlanta, Georgia",2025-02-21,2025-02-22,1.0,2025-02-20,2025-02-22,1.0,2025-02-19,2025-02-22,1.0,...,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
1,"Atlanta, Georgia",2025-02-22,2025-02-23,1.0,2025-02-21,2025-02-23,1.0,2025-02-20,2025-02-23,1.0,...,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
2,"Atlanta, Georgia",2025-02-23,2025-02-24,0.0,2025-02-22,2025-02-24,1.0,2025-02-21,2025-02-24,1.0,...,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
3,"Atlanta, Georgia",2025-02-24,2025-02-25,0.0,2025-02-23,2025-02-25,0.0,2025-02-22,2025-02-25,1.0,...,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
4,"Atlanta, Georgia",2025-02-25,2025-02-26,0.0,2025-02-24,2025-02-26,0.0,2025-02-23,2025-02-26,0.0,...,3.0,2.0,mls,mls_1,0,Mercedes-Benz Stadium,"Atlanta, Georgia",42500,2017,2025-02-22 18:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22578,"Winnipeg, Manitoba",2026-04-11,2026-04-12,1.0,2026-04-10,2026-04-12,1.0,2026-04-09,2026-04-12,1.0,...,NaN,NaN,nhl,nhl_1,0,Canada Life Centre,"Winnipeg, Manitoba",15321,2004,2026-04-11 18:00:00
22579,"Winnipeg, Manitoba",2026-04-12,2026-04-13,0.0,2026-04-11,2026-04-13,1.0,2026-04-10,2026-04-13,1.0,...,NaN,NaN,nhl,nhl_1,0,Canada Life Centre,"Winnipeg, Manitoba",15321,2004,2026-04-11 18:00:00
22580,"Winnipeg, Manitoba",2026-04-13,2026-04-14,0.0,2026-04-12,2026-04-14,0.0,2026-04-11,2026-04-14,1.0,...,NaN,NaN,nhl,nhl_1,0,Canada Life Centre,"Winnipeg, Manitoba",15321,2004,2026-04-11 18:00:00
22581,"Winnipeg, Manitoba",2026-04-14,2026-04-15,0.0,2026-04-13,2026-04-15,0.0,2026-04-12,2026-04-15,0.0,...,NaN,NaN,nhl,nhl_1,0,Canada Life Centre,"Winnipeg, Manitoba",15321,2004,2026-04-11 18:00:00
22582,"Winnipeg, Manitoba",2026-04-15,2026-04-16,1.0,2026-04-14,2026-04-16,1.0,2026-04-13,2026-04-16,1.0,...,NaN,NaN,nhl,nhl_1,0,Canada Life Centre,"Winnipeg, Manitoba",15321,2004,2026-04-16 19:00:00

In [5]:
# find highest five day total for each metro
agg_df = games_df.copy()
agg_df['max_five_day_total'] = agg_df.groupby(by='metro_area')['five_day_total'].transform('max')
agg_df = agg_df[['metro_area', 'five_day_total', 'five_day_start_date', 'five_day_end_date', 'max_five_day_total']]
agg_df = agg_df[agg_df['max_five_day_total']==agg_df['five_day_total']].drop_duplicates().reset_index(drop=True)
agg_df

,metro_area,five_day_total,five_day_start_date,five_day_end_date,max_five_day_total
0,"Atlanta, Georgia",2.0,2025-10-18,2025-10-22,2.0
1,"Austin, Texas",1.0,2025-02-18,2025-02-22,1.0
2,"Austin, Texas",1.0,2025-02-19,2025-02-23,1.0
3,"Austin, Texas",1.0,2025-02-20,2025-02-24,1.0
4,"Austin, Texas",1.0,2025-02-21,2025-02-25,1.0
...,...,...,...,...,...
2663,"Winnipeg, Manitoba",1.0,2026-04-08,2026-04-12,1.0
2664,"Winnipeg, Manitoba",1.0,2026-04-09,2026-04-13,1.0
2665,"Winnipeg, Manitoba",1.0,2026-04-10,2026-04-14,1.0
2666,"Winnipeg, Manitoba",1.0,2026-04-11,2026-04-15,1.0
2667,"Winnipeg, Manitoba",1.0,2026-04-12,2026-04-16,1.0

In [6]:
agg_df_cities = agg_df[['metro_area', 'max_five_day_total']].drop_duplicates(keep='first').reset_index(drop=True)
agg_df_cities

                     metro_area  max_five_day_total
0              Atlanta, Georgia                 2.0
1                 Austin, Texas                 1.0
2           Baltimore, Maryland                 2.0
3         Boston, Massachusetts                 3.0
4             Buffalo, New York                 2.0
5              Calgary, Alberta                 1.0
6     Charlotte, North Carolina                 2.0
7             Chicago, Illinois                 3.0
8              Cincinnati, Ohio                 2.0
9               Cleveland, Ohio                 2.0
10               Columbus, Ohio                 2.0
11                Dallas, Texas                 3.0
12             Denver, Colorado                 3.0
13            Detroit, Michigan                 3.0
14            Edmonton, Alberta                 1.0
15         Green Bay, Wisconsin                 1.0
16               Houston, Texas                 2.0
17        Indianapolis, Indiana                 2.0
18        Jacksonville, Florida                 1.0
19            Las Vegas, Nevada                 2.0
20      Los Angeles, California                 5.0
21           Memphis, Tennessee                 1.0
22               Miami, Florida                 3.0
23         Milwaukee, Wisconsin                 1.0
24       Minneapolis, Minnesota                 3.0
25             Montreal, Quebec                 1.0
26         Nashville, Tennessee                 1.0
27      New York City, New York                 5.0
28             Orlando, Florida                 1.0
29              Ottawa, Ontario                 1.0
30   Philadelphia, Pennsylvania                 3.0
31             Phoenix, Arizona                 2.0
32     Pittsburgh, Pennsylvania                 2.0
33             Portland, Oregon                 1.0
34      Raleigh, North Carolina                 1.0
35       Sacramento, California                 1.0
36         Salt Lake City, Utah                 2.0
37           San Antonio, Texas                 1.0
38        San Diego, California                 2.0
39    San Francisco, California                 3.0
40          Seattle, Washington                 2.0
41               Tampa, Florida                 1.0
42             Toronto, Ontario                 2.0
43  Vancouver, British Columbia                 2.0
44             Washington, D.C.                 3.0
45           Winnipeg, Manitoba                 1.0

In [18]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from tqdm import tqdm
tqdm.pandas()
geolocator = Nominatim(user_agent='na_cities')
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

In [15]:
geocode("san antonio, texas")

Location(San Antonio, Bexar County, Texas, United States of America, (29.4246002, -98.4951405, 0.0))

In [19]:
agg_df_loc = agg_df_cities.copy()
agg_df_loc['loc'] = agg_df_loc['metro_area'].progress_apply(geocode)
agg_df_loc

100%|██████████| 46/46 [00:47<00:00,  1.03s/it]

,metro_area,max_five_day_total,loc
0,"Atlanta, Georgia",2.0,"(Atlanta, Fulton County, Georgia, United State..."
1,"Austin, Texas",1.0,"(Austin, Travis County, Texas, United States o..."
2,"Baltimore, Maryland",2.0,"(Baltimore, Maryland, United States of America..."
3,"Boston, Massachusetts",3.0,"(Boston, Suffolk County, Massachusetts, United..."
4,"Buffalo, New York",2.0,"(Buffalo, Erie County, New York, United States..."
5,"Calgary, Alberta",1.0,"(Calgary, Alberta, Canada, (51.0456064, -114.0..."
6,"Charlotte, North Carolina",2.0,"(Charlotte, Mecklenburg County, North Carolina..."
7,"Chicago, Illinois",3.0,"(Chicago, South Chicago Township, Cook County,..."
8,"Cincinnati, Ohio",2.0,"(Cincinnati, Hamilton County, Ohio, 45202, Uni..."
9,"Cleveland, Ohio",2.0,"(Cleveland, Cuyahoga County, Ohio, United Stat..."
10,"Columbus, Ohio",2.0,"(Columbus, Franklin County, Ohio, United State..."
11,"Dallas, Texas",3.0,"(Dallas, Dallas County, Texas, United States o..."
12,"Denver, Colorado",3.0,"(Denver, Colorado, United States of America, (..."
13,"Detroit, Michigan",3.0,"(Detroit, Wayne County, Michigan, United State..."
14,"Edmonton, Alberta",1.0,"(Edmonton, Alberta, Canada, (53.5462055, -113...."
15,"Green Bay, Wisconsin",1.0,"(Green Bay, Brown County, Wisconsin, United St..."
16,"Houston, Texas",2.0,"(Houston, Harris County, Texas, United States ..."
17,"Indianapolis, Indiana",2.0,"(Indianapolis, Marion County, Indiana, United ..."
18,"Jacksonville, Florida",1.0,"(Jacksonville, Duval County, Florida, United S..."
19,"Las Vegas, Nevada",2.0,"(Las Vegas, Clark County, Nevada, United State..."
20,"Los Angeles, California",5.0,"(Los Angeles, Los Angeles County, California, ..."
21,"Memphis, Tennessee",1.0,"(Memphis, Shelby County, West Tennessee, Tenne..."
22,"Miami, Florida",3.0,"(Miami, Miami-Dade County, Florida, United Sta..."
23,"Milwaukee, Wisconsin",1.0,"(Milwaukee, Milwaukee County, Wisconsin, Unite..."
24,"Minneapolis, Minnesota",3.0,"(Minneapolis, Hennepin County, Minnesota, Unit..."
25,"Montreal, Quebec",1.0,"(Montréal, Agglomération de Montréal, Montréal..."
26,"Nashville, Tennessee",1.0,"(Nashville, Davidson County, Middle Tennessee,..."
27,"New York City, New York",5.0,"(City of New York, New York, United States of ..."
28,"Orlando, Florida",1.0,"(Orlando, Orange County, Florida, United State..."
29,"Ottawa, Ontario",1.0,"(Ottawa, Eastern Ontario, Ontario, Canada, (45..."
30,"Philadelphia, Pennsylvania",3.0,"(Philadelphia, Philadelphia County, Pennsylvan..."
31,"Phoenix, Arizona",2.0,"(Phoenix, Maricopa County, Arizona, United Sta..."
32,"Pittsburgh, Pennsylvania",2.0,"(Pittsburgh, Allegheny County, Pennsylvania, U..."
33,"Portland, Oregon",1.0,"(Portland, Multnomah County, Oregon, United St..."
34,"Raleigh, North Carolina",1.0,"(Raleigh, Wake County, North Carolina, United ..."
35,"Sacramento, California",1.0,"(Sacramento, Sacramento County, California, Un..."
36,"Salt Lake City, Utah",2.0,"(Salt Lake City, Salt Lake County, Utah, Unite..."
37,"San Antonio, Texas",1.0,"(San Antonio, Bexar County, Texas, United Stat..."
38,"San Diego, California",2.0,"(San Diego, San Diego County, California, Unit..."
39,"San Francisco, California",3.0,"(San Francisco, California, United States of A..."
40,"Seattle, Washington",2.0,"(Seattle, King County, Washington, United Stat..."
41,"Tampa, Florida",1.0,"(Tampa, Hillsborough County, Florida, United S..."
42,"Toronto, Ontario",2.0,"(Toronto, Golden Horseshoe, Ontario, Canada, (..."
43,"Vancouver, British Columbia",2.0,"(Vancouver, Metro Vancouver Regional District,..."
44,"Washington, D.C.",3.0,"(Washington, District of Columbia, United Stat..."
45,"Winnipeg, Manitoba",1.0,"(Winnipeg, Manitoba, Canada, (49.8955367, -97...."

In [25]:
agg_df_loc['latitude'] = agg_df_loc['loc'].apply(lambda x: x.latitude)
agg_df_loc['longitude'] = agg_df_loc['loc'].apply(lambda x: x.longitude)
agg_df_loc

,metro_area,max_five_day_total,loc,latitude,longitude
0,"Atlanta, Georgia",2.0,"(Atlanta, Fulton County, Georgia, United State...",33.754466,-84.389815
1,"Austin, Texas",1.0,"(Austin, Travis County, Texas, United States o...",30.271129,-97.743700
2,"Baltimore, Maryland",2.0,"(Baltimore, Maryland, United States of America...",39.290882,-76.610759
3,"Boston, Massachusetts",3.0,"(Boston, Suffolk County, Massachusetts, United...",42.355433,-71.060511
4,"Buffalo, New York",2.0,"(Buffalo, Erie County, New York, United States...",42.886717,-78.878392
5,"Calgary, Alberta",1.0,"(Calgary, Alberta, Canada, (51.0456064, -114.0...",51.045606,-114.057541
6,"Charlotte, North Carolina",2.0,"(Charlotte, Mecklenburg County, North Carolina...",35.227209,-80.843083
7,"Chicago, Illinois",3.0,"(Chicago, South Chicago Township, Cook County,...",41.875562,-87.624421
8,"Cincinnati, Ohio",2.0,"(Cincinnati, Hamilton County, Ohio, 45202, Uni...",39.101454,-84.512460
9,"Cleveland, Ohio",2.0,"(Cleveland, Cuyahoga County, Ohio, United Stat...",41.499657,-81.693677
10,"Columbus, Ohio",2.0,"(Columbus, Franklin County, Ohio, United State...",39.962260,-83.000707
11,"Dallas, Texas",3.0,"(Dallas, Dallas County, Texas, United States o...",32.776272,-96.796856
12,"Denver, Colorado",3.0,"(Denver, Colorado, United States of America, (...",39.739236,-104.984862
13,"Detroit, Michigan",3.0,"(Detroit, Wayne County, Michigan, United State...",42.331551,-83.046640
14,"Edmonton, Alberta",1.0,"(Edmonton, Alberta, Canada, (53.5462055, -113....",53.546205,-113.491241
15,"Green Bay, Wisconsin",1.0,"(Green Bay, Brown County, Wisconsin, United St...",44.512638,-88.012579
16,"Houston, Texas",2.0,"(Houston, Harris County, Texas, United States ...",29.758938,-95.367697
17,"Indianapolis, Indiana",2.0,"(Indianapolis, Marion County, Indiana, United ...",39.768333,-86.158350
18,"Jacksonville, Florida",1.0,"(Jacksonville, Duval County, Florida, United S...",30.332184,-81.655651
19,"Las Vegas, Nevada",2.0,"(Las Vegas, Clark County, Nevada, United State...",36.167426,-115.148413
20,"Los Angeles, California",5.0,"(Los Angeles, Los Angeles County, California, ...",34.053691,-118.242766
21,"Memphis, Tennessee",1.0,"(Memphis, Shelby County, West Tennessee, Tenne...",35.146025,-90.051764
22,"Miami, Florida",3.0,"(Miami, Miami-Dade County, Florida, United Sta...",25.774157,-80.193597
23,"Milwaukee, Wisconsin",1.0,"(Milwaukee, Milwaukee County, Wisconsin, Unite...",43.038648,-87.909075
24,"Minneapolis, Minnesota",3.0,"(Minneapolis, Hennepin County, Minnesota, Unit...",44.977300,-93.265469
25,"Montreal, Quebec",1.0,"(Montréal, Agglomération de Montréal, Montréal...",45.503182,-73.569806
26,"Nashville, Tennessee",1.0,"(Nashville, Davidson County, Middle Tennessee,...",36.162277,-86.774298
27,"New York City, New York",5.0,"(City of New York, New York, United States of ...",40.712728,-74.006015
28,"Orlando, Florida",1.0,"(Orlando, Orange County, Florida, United State...",28.542111,-81.379030
29,"Ottawa, Ontario",1.0,"(Ottawa, Eastern Ontario, Ontario, Canada, (45...",45.420878,-75.690111
30,"Philadelphia, Pennsylvania",3.0,"(Philadelphia, Philadelphia County, Pennsylvan...",39.952724,-75.163526
31,"Phoenix, Arizona",2.0,"(Phoenix, Maricopa County, Arizona, United Sta...",33.448437,-112.074141
32,"Pittsburgh, Pennsylvania",2.0,"(Pittsburgh, Allegheny County, Pennsylvania, U...",40.441694,-79.990086
33,"Portland, Oregon",1.0,"(Portland, Multnomah County, Oregon, United St...",45.520247,-122.674194
34,"Raleigh, North Carolina",1.0,"(Raleigh, Wake County, North Carolina, United ...",35.780398,-78.639099
35,"Sacramento, California",1.0,"(Sacramento, Sacramento County, California, Un...",38.581061,-121.493895
36,"Salt Lake City, Utah",2.0,"(Salt Lake City, Salt Lake County, Utah, Unite...",40.759620,-111.886797
37,"San Antonio, Texas",1.0,"(San Antonio, Bexar County, Texas, United Stat...",29.424600,-98.495141
38,"San Diego, California",2.0,"(San Diego, San Diego County, California, Unit...",32.717420,-117.162772
39,"San Francisco, California",3.0,"(San Francisco, California, United States of A...",37.779259,-122.419329
40,"Seattle, Washington",2.0,"(Seattle, King County, Washington, United Stat...",47.603832,-122.330062
41,"Tampa, Florida",1.0,"(Tampa, Hillsborough County, Florida, United S...",27.947760,-82.458444
42,"Toronto, Ontario",2.0,"(Toronto, Golden Horseshoe, Ontario, Canada, (...",43.653482,-79.383935
43,"Vancouver, British Columbia",2.0,"(Vancouver, Metro Vancouver Regional District,...",49.260872,-123.113952
44,"Washington, D.C.",3.0,"(Washington, District of Columbia, United Stat...",38.895037,-77.036543
45,"Winnipeg, Manitoba",1.0,"(Winnipeg, Manitoba, Canada, (49.8955367, -97....",49.895537,-97.138458

In [ ]:
fig = px.scatter_geo(agg_df_loc, hover_name='metro_area', lat='latitude', lon='longitude', color='max_five_day_total', size='max_five_day_total', scope='north america', size_max=40)
# Use a conic projection and wider bounds so Canada is included while still highlighting subunit borders
fig.update_geos(center={'lat': 50, 'lon': -100}, lataxis_range=[25, 75], lonaxis_range=[-150, -50], showcountries=True, showcoastlines=True, showsubunits=True, subunitcolor='black', subunitwidth=1.5, coastlinecolor='black', coastlinewidth=0.8, projection_type='conic conformal')
# Increase the overall figure size and add a title
fig.update_layout(width=1200, height=800, title='Max Five Day Total by Metro Area (US + Canada)')
fig.show()